### ISSUE TITLE
mac scripting no longer working / supported

### ISSUE THREAD

**Issue by dsldsl** [lohriialo/photoshop-scripting-python#15]
appscript is no longer actively developed / supported and doesn't seem to work in the newest mac OS.  

![image](https://user-images.githubusercontent.com/50015/130561406-02f29fa5-d41b-4c45-b559-ba3a4cdfe02e.png)

**Comment by oh-ok** [comment]
Mac scripting is still supported, it's just that the default way appscript get's the terminology (via an AETE event) is deprecated and no longer supported in recent Photoshop versions. You just need to specify `terms="sdef"` as a parameter when you create the Photoshop instance in Python like so:

```
from appscript import app
ps = app(id="com.adobe.Photoshop", terms="sdef")
ps.current_document
```
(I'm using id= here, you can still use name or path)

Also in recent versions of Photoshop, the syntax for referencing files has changed. `ps.open(mactypes.Alias(filename))` no longer works, since the AppleScript syntax has changed from
`tell application "..." to open "/directory/example_file.png" as file` (an alias/file descriptor)
to
`tell application "..." to open file "/directory/example_file.png"` (an object specifier of the file class)

For that, you'll need to also create an app for macOS' "System Events" app, and get a file object by name (which is the absolute path) like so:
```
from appscript import app
ps = app(id="com.adobe.Photoshop", terms="sdef")
sysevents = app("System Events")


ps.open(sysevents.files["/directory/example_file.png"])
```

The documentation here should be updated to reflect these changes I think.

**Comment by lohriialo** [comment]
fixed by https://github.com/lohriialo/photoshop-scripting-python/commit/2a4456ad3d732c24d5634798f9d865f28f4d2b4e
